POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IlRoZSBUZXN0dXNlciIsImlkIjoiNjEzNGFjNTQxODEwMmExNTgwZTAwYzU2IiwiaWF0IjoxNjMwODQxOTg1fQ.efaycQX2FStTx2EzoX7XhqolxzLkymiJYnbQebjUSxI

{
    "title": "The Blogster",
    "author": "Spede Pasanen",
    "url": "www.blogiosoite.com",
    "likes": 10,
    "userId": "6134ac5418102a1580e00c56"
}